import Head from "next/head";
import Image from "next/image";
import Navbar from "../../components/navbar";
import Footer from "../../components/footer";
import hp from "../../public/images/herapheri.jpg";
import i1 from "../../public/images/frzi.jpg";
import i2 from "../../public/images/rs.jpg";
import i3 from "../../public/images/drishyam.jpg";
import i4 from "../../public/images/chris.jpg";
import { FaRegPlayCircle } from "react-icons/fa";
import { VscAdd } from "react-icons/vsc";
import { BiBlock } from "react-icons/bi";
import { FiPlay } from "react-icons/fi";
import { TfiCommentAlt } from "react-icons/tfi";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from "react-responsive-carousel";
import Movie from "../../components/movie";
import Movie1 from "../../components/movie/movie2";
import Movie2 from "../../components/movie/movie3";
import Movie3 from "../../components/movie/movie4";
export default function Home() {
  return (
    <>
      <Head>
        <title>AMAZON PRIME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link href="/dist/output.css" rel="stylesheet" /> */}
      </Head>
      <main className="bg-[#0f161f]">
        <Navbar />
        <Carousel className="mx-10">
          <div>
            <Image src={i1} alt="image1" className="h-96 max-sm:h-60" />
          </div>
          <div>
            <Image src={i2} alt="image2" className="h-96 max-sm:h-60" />
          </div>
          <div>
            <Image src={i3} alt="image3" className="h-96 max-sm:h-60" />
          </div>
          <div>
            <Image src={i4} alt="image4" className="h-96 max-sm:h-60" />
          </div>
        </Carousel>
        <div className="h-full w-full ">
          <span className="text-[#8197a4] px-10">Amazon Original Series</span>
          <div className="flex-col justify-center items-center">
            <div className=" flex justify-center items-center gap-8 my-8 max-sm:flex-col sm:mx-12">
             <Movie/>
             <Movie1/>
             <Movie2/>
             <Movie3/>
            </div>
            <div className="flex justify-center items-center gap-8 my-8 max-sm:flex-col sm:mx-12">
            <Movie/>
             <Movie1/>
             <Movie2/>
             <Movie3/>
            </div>
            <div className="flex justify-center items-center gap-8 my-8 max-sm:flex-col sm:mx-12">
            <Movie/>
             <Movie1/>
             <Movie2/>
             <Movie3/>
            </div>
          </div>
        </div>
        {/* <div className="h-full w-full my-4 px-6">
          <span className="text-white text-3xl px-4 font-semibold">
            Recommended movies
          </span>
        </div> */}

        <Footer />
      </main>
    </>
  );
}
