import Head from "next/head";
import Image from "next/image";
import Navbar from "../../components/navbar";
import Footer from "../../components/footer";
import hp from "../../public/images/herapheri.jpg";
import i1 from "../../public/images/frzi.jpg";
import i2 from "../../public/images/rs.jpg";
import i3 from "../../public/images/drishyam.jpg";
import i4 from "../../public/images/chris.jpg";
import { FaRegPlayCircle } from "react-icons/fa";
import { VscAdd } from "react-icons/vsc";
import { BiBlock } from "react-icons/bi";
import { FiPlay } from "react-icons/fi";
import { TfiCommentAlt } from "react-icons/tfi";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from "react-responsive-carousel";
export default function Home() {
  return (
    <>
      <Head>
        <title>AMAZON PRIME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link href="/dist/output.css" rel="stylesheet" /> */}
      </Head>
      <main className="bg-[#0f161f]">
        <Navbar />
        <Carousel className="mx-10">
          <div>
            <Image src={i1} alt="image1" className="h-96 max-sm:h-60" />
          </div>
          <div>
            <Image src={i2} alt="image2" className="h-96 max-sm:h-60" />
          </div>
          <div>
            <Image src={i3} alt="image3" className="h-96 max-sm:h-60" />
          </div>
          <div>
            <Image src={i4} alt="image4" className="h-96 max-sm:h-60" />
          </div>
        </Carousel>
        <div className="h-full w-full ">
          <span className="text-[#8197a4] px-10">Amazon Original Series</span>
          <div className="flex-col justify-center items-center">
            <div className=" flex justify-center items-center gap-8 my-8 max-sm:flex-col sm:mx-12">
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={hp} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Hera Pheri</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={hp} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block ">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Farzi</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={hp} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block ">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Hera Pheri</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={hp} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block ">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Farzi</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex justify-center items-center gap-8 my-8 max-sm:flex-col sm:mx-12">
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={i3} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block ">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Hera Pheri</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={i3} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block ">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Farzi</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={i3} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block ">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Hera Pheri</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={i3} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block ">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Farzi</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex justify-center items-center gap-8 my-8 max-sm:flex-col sm:mx-12">
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={i4} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block ">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Hera Pheri</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={i4} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block ">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Farzi</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={i4} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block ">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Hera Pheri</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
              <div className="hover:z-20 w-72  hover:w-80  group relative ease-in-out transition duration-400 delay-10 hover:scale-110">
                <Image src={i4} className="w-full" alt="image" />
                <div className="bg-[#18232f] absolute hidden group-hover:block ">
                  <div className="text-white flex ">
                    <div className="w-1/2 h-full flex justify-start items-center gap-3 px-4">
                      <button>
                        <FaRegPlayCircle className="h-10" />
                      </button>
                      <span>Play</span>
                    </div>
                    <div className="w-1/2 h-full flex justify-end items-center gap-4 px-4">
                      <button>
                        <FiPlay className="h-10" />
                      </button>
                      <button>
                        <VscAdd className="h-10" />
                      </button>
                      <button>
                        <BiBlock className="h-10" />
                      </button>
                    </div>
                  </div>
                  <div className="text-white p-2 px-4">
                    <h3>Farzi</h3>
                    <p className="my-3">
                      Three unemployed men find the answer to all their money
                      problems when they recieve a call from a kidnapper
                    </p>
                    <p className="flex items-center gap-5 mt-4">
                      2hr 13min
                      <span>2000</span>
                      <TfiCommentAlt />
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* <div className="h-full w-full my-4 px-6">
          <span className="text-white text-3xl px-4 font-semibold">
            Recommended movies
          </span>
        </div> */}

        <Footer />
      </main>
    </>
  );
}
